const animeDetails = [
    {
      "anime_name": "One Piece",
      "voice_artist": "Mayumi Tanaka, Colleen Clinkenbeard",
      "writer": "Eiichiro Oda",
      "director": "Kōnosuke Uda",
      "year_of_release": 1999,
      "image_link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxxiYdnxLRy6kuWO91Jiwy_L0b9XhWe_M71Q&s",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Ongoing",
      "total_episodes": 1000,
      "imdb_link": "https://www.imdb.com/title/tt0388629/",
      "watch_link": "https://animeflix.gg/?anime=one-piece",
      "popularity": 100
    },
    {
      "anime_name": "Attack on Titan",
      "voice_artist": "Yuki Kaji, Yui Ishikawa",
      "writer": "Hajime Isayama",
      "director": "Tetsurō Araki",
      "year_of_release": 2013,
      "image_link": "https://m.media-amazon.com/images/M/MV5BNDFjYTIxMjctYTQ2ZC00OGQ4LWE3OGYtNDdiMzNiNDZlMDAwXkEyXkFqcGdeQXVyNzI3NjY3NjQ@._V1_FMjpg_UX1000_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-MA",
      "status": "Ongoing",
      "total_episodes": 75,
      "imdb_link": "https://www.imdb.com/title/tt2560140/",
      "watch_link": "https://animeflix.gg/?anime=shingeki-no-kyojin",
      "popularity": 95
    },
    {
      "anime_name": "Naruto",
      "voice_artist": "Junko Takeuchi, Maile Flanagan",
      "writer": "Masashi Kishimoto",
      "director": "Hayato Date",
      "year_of_release": 2002,
      "image_link": "https://m.media-amazon.com/images/M/MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 220,
      "imdb_link": "https://www.imdb.com/title/tt0409591/",
      "watch_link": "https://animeflix.gg/?anime=naruto",
      "popularity": 90
    },
    {
      "anime_name": "Demon Slayer: Kimetsu no Yaiba",
      "voice_artist": "Natsuki Hanae, Zach Aguilar",
      "writer": "Koyoharu Gotouge",
      "director": "Haruo Sotozaki",
      "year_of_release": 2019,
      "image_link": "https://m.media-amazon.com/images/M/MV5BZjZjNzI5MDctY2Y4YS00NmM4LTljMmItZTFkOTExNGI3ODRhXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-MA",
      "status": "Completed",
      "total_episodes": 26,
      "imdb_link": "https://www.imdb.com/title/tt9335498/",
      "watch_link": "https://animeflix.gg/?anime=kimetsu-no-yaiba",
      "popularity": 85
    },
    {
      "anime_name": "My Hero Academia",
      "voice_artist": "Daiki Yamashita, Justin Briner",
      "writer": "Kōhei Horikoshi",
      "director": "Kenji Nagasaki",
      "year_of_release": 2016,
      "image_link": "https://images-cdn.ubuy.co.in/63578559ec790443a15aa293-hagakure-mha-midoriya-izuku-deku-light.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Ongoing",
      "total_episodes": 113,
      "imdb_link": "https://www.imdb.com/title/tt5626028/",
      "watch_link": "https://animeflix.gg/?anime=boku-no-hero-academia",
      "popularity": 80
    },
    {
      "anime_name": "Dragon Ball Z",
      "voice_artist": "Masako Nozawa, Sean Schemmel",
      "writer": "Akira Toriyama",
      "director": "Daisuke Nishio",
      "year_of_release": 1989,
      "image_link": "https://assetsio.reedpopcdn.com/Dragon-Ball-Super-Saiyan-3-Goku.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp",
      "duration": "24 min per episode",
      "age_rating": "TV-PG",
      "status": "Completed",
      "total_episodes": 291,
      "imdb_link": "https://www.imdb.com/title/tt0214341/",
      "watch_link": "https://animeflix.gg/?anime=dragon-ball-z",
      "popularity": 75
    },
    {
      "anime_name": "Death Note",
      "voice_artist": "Mamoru Miyano, Kappei Yamaguchi",
      "writer": "Tsugumi Ohba",
      "director": "Tetsurō Araki",
      "year_of_release": 2006,
      "image_link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmO1nsCx6rEMVVLuxgM2ii1eNrwOjRtcoKjQ&s",
      "duration": "23 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 37,
      "imdb_link": "https://www.imdb.com/title/tt0877057/",
      "watch_link": "https://animeflix.gg/?anime=death-note",
      "popularity": 70
    },
    {
      "anime_name": "Fullmetal Alchemist: Brotherhood",
      "voice_artist": "Romi Park, Rie Kugimiya",
      "writer": "Hiromu Arakawa",
      "director": "Yasuhiro Irie",
      "year_of_release": 2009,
      "image_link": "https://m.media-amazon.com/images/M/MV5BZmEzN2YzOTItMDI5MS00MGU4LWI1NWQtOTg5ZThhNGQwYTEzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 64,
      "imdb_link": "https://www.imdb.com/title/tt1355642/",
      "watch_link": "https://animeflix.gg/?anime=hagane-no-renkinjutsushi-fullmetal-alchemist",
      "popularity": 65
    },
    {
      "anime_name": "Tokyo Ghoul",
      "voice_artist": "Natsuki Hanae, Austin Tindle",
      "writer": "Sui Ishida",
      "director": "Shuhei Morita",
      "year_of_release": 2014,
      "image_link": "https://images.squarespace-cdn.com/content/v1/54fc8146e4b02a22841f4df7/adae5b77-380f-4c37-ae1a-97323e66ed55/Art_of_1.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-MA",
      "status": "Completed",
      "total_episodes": 48,
      "imdb_link": "https://www.imdb.com/title/tt3741634/",
      "watch_link": "https://animeflix.gg/?anime=ghou-ling-tokyo-",
      "popularity": 60
    },
    {
      "anime_name": "Your Lie in April",
      "voice_artist": "Natsuki Hanae, Risa Taneda",
      "writer": "Naoshi Arakawa",
      "director": "Kyōhei Ishiguro",
      "year_of_release": 2014,
      "image_link": "https://i.pinimg.com/236x/bb/d7/27/bbd727055edbfada10fd94e5a3e3cc55.jpg",
      "duration": "22 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 22,
      "imdb_link": "https://www.imdb.com/title/tt3895150/",
      "watch_link": "https://animeflix.gg/search/Your%20Lie%20in%20April?anime=shigatsu-wa-kimi-no-uso",
      "popularity": 55
    },
    {
      "anime_name": "Sword Art Online",
      "voice_artist": "Yoshitsugu Matsuoka, Bryce Papenbrook",
      "writer": "Reki Kawahara",
      "director": "Tomohiko Itō",
      "year_of_release": 2012,
      "image_link": "https://m.media-amazon.com/images/M/MV5BYjY4MDU2YjMtNzY1MC00ODg1LWIwMzYtMWE5YTA3YTI4ZjMxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Ongoing",
      "total_episodes": 100,
      "imdb_link": "https://www.imdb.com/title/tt2250192/",
      "watch_link": "https://animeflix.gg/search/Sword%20Art%20Online?anime=sword-art-online",
      "popularity": 50
    },
    {
      "anime_name": "Neon Genesis Evangelion",
      "voice_artist": "Megumi Ogata, Spike Spencer",
      "writer": "Hideaki Anno",
      "director": "Hideaki Anno, Kazuya Tsurumaki",
      "year_of_release": 1995,
      "image_link": "https://m.media-amazon.com/images/M/MV5BMTc4YTY0MDUtYWNmMi00NTRiLWE4NmItM2JiMmIzYmEwNGQzXkEyXkFqcGdeQXVyNTkwNzYyODM@._V1_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 26,
      "imdb_link": "https://www.imdb.com/title/tt0112159/",
      "watch_link": "https://animeflix.gg/search/Neon%20Genesis%20Evangelion?anime=shin-seiki-evangelion",
      "popularity": 45
    },
    {
      "anime_name": "Fairy Tail",
      "voice_artist": "Tetsuya Kakihara, Todd Haberkorn",
      "writer": "Hiro Mashima",
      "director": "Shinji Ishihira",
      "year_of_release": 2009,
      "image_link": "https://m.media-amazon.com/images/M/MV5BMzZjNmRhNWQtNTAyYy00Yjk2LWE0NzUtMmYyNTU0YTE5NjJiXkEyXkFqcGdeQXVyNjI4OTE5OTM@._V1_FMjpg_UX1000_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 328,
      "imdb_link": "https://www.imdb.com/title/tt1528406/",
      "watch_link": "https://animeflix.gg/search/Fairy%20Tail?anime=fairy-tail",
      "popularity": 40
    },
    {
      "anime_name": "Hunter x Hunter (2011)",
      "voice_artist": "Megumi Han, Erica Mendez",
      "writer": "Yoshihiro Togashi",
      "director": "Hiroshi Kōjina",
      "year_of_release": 2011,
      "image_link": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR82DF0QQYyoPYIgQeh1ONj-N9NOhoXkL8zdg&s",
      "duration": "23 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 148,
      "imdb_link": "https://www.imdb.com/title/tt2098220/",
      "watch_link": "https://animeflix.gg/search/Hunter%20x%20Hunter%20(2011)?anime=hunterhunter-2011",
      "popularity": 35
    },
    {
      "anime_name": "Code Geass: Lelouch of the Rebellion",
      "voice_artist": "Jun Fukuyama, Johnny Yong Bosch",
      "writer": "Ichirō Ōkouchi",
      "director": "Gorō Taniguchi",
      "year_of_release": 2006,
      "image_link": "https://upload.wikimedia.org/wikipedia/en/7/74/Code_Geass_R1_box_set_cover.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 50,
      "imdb_link": "https://www.imdb.com/title/tt0994314/",
      "watch_link": "https://animeflix.gg/search/Code%20Geass:%20Lelouch%20of%20the%20Rebellion?anime=code-geass-hangyaku-no-lelouch",
      "popularity": 30
    },
    {
      "anime_name": "Cowboy Bebop",
      "voice_artist": "Kōichi Yamadera, Steve Blum",
      "writer": "Shinichirō Watanabe",
      "director": "Shinichirō Watanabe",
      "year_of_release": 1998,
      "image_link": "https://upload.wikimedia.org/wikipedia/en/a/a9/Cowboy_Bebop_key_visual.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 26,
      "imdb_link": "https://www.imdb.com/title/tt0214341/",
      "watch_link": "https://animeflix.gg/search/Cowboy%20Bebop?anime=cowboy-bebop-2-2",
      "popularity": 25
    },
    {
      "anime_name": "Steins;Gate",
      "voice_artist": "Asami Imai, Mamoru Miyano",
      "writer": "Jukki Hanada",
      "director": "Hiroshi Hamasaki",
      "year_of_release": 2011,
      "image_link": "https://m.media-amazon.com/images/M/MV5BMjUxMzE4ZDctODNjMS00MzIwLThjNDktODkwYjc5YWU0MDc0XkEyXkFqcGdeQXVyNjc3OTE4Nzk@._V1_FMjpg_UX1000_.jpg",
      "duration": "24 min per episode",
      "age_rating": "TV-14",
      "status": "Completed",
      "total_episodes": 24,
      "imdb_link": "https://www.imdb.com/title/tt1910272/",
      "watch_link": "https://animeflix.gg/search/Steins;Gate?anime=steinsgate",
      "popularity": 20
    },
    {
      "anime_name": "Spirited Away",
      "voice_artist": "Rumi Hiiragi, Miyu Irino",
      "writer": "Hayao Miyazaki",
      "director": "Hayao Miyazaki",
      "year_of_release": 2001,
      "image_link": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
      "duration": "2h 5min",
      "age_rating": "PG",
      "status": "Completed",
      "total_episodes": 1,
      "imdb_link": "https://www.imdb.com/title/tt0245429/",
      "watch_link": "https://animeflix.gg/search/Spirited%20Away?anime=sen-to-chihiro-no-kamikakushi",
      "popularity": 15
    }
  ];

  export default animeDetails;
  