const movieData = [
    {
      "movie_name": "Inception",
      "male_lead": "Leonardo DiCaprio",
      "female_lead": "Marion Cotillard",
      "director": "Christopher Nolan",
      "year_of_release": 2010,
      "image_link": "https://example.com/inception.jpg",
      "duration": "2h 28min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt1375666/"
    },
    {
      "movie_name": "The Shawshank Redemption",
      "male_lead": "Tim Robbins",
      "female_lead": "",
      "director": "Frank Darabont",
      "year_of_release": 1994,
      "image_link": "https://example.com/shawshank_redemption.jpg",
      "duration": "2h 22min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0111161/"
    },
    {
      "movie_name": "The Dark Knight",
      "male_lead": "Christian Bale",
      "female_lead": "Maggie Gyllenhaal",
      "director": "Christopher Nolan",
      "year_of_release": 2008,
      "image_link": "https://example.com/the_dark_knight.jpg",
      "duration": "2h 32min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0468569/"
    },
    {
      "movie_name": "The Godfather",
      "male_lead": "Marlon Brando",
      "female_lead": "Diane Keaton",
      "director": "Francis Ford Coppola",
      "year_of_release": 1972,
      "image_link": "https://example.com/the_godfather.jpg",
      "duration": "2h 55min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0068646/"
    },
    {
      "movie_name": "Avengers: Endgame",
      "male_lead": "Robert Downey Jr.",
      "female_lead": "Scarlett Johansson",
      "director": "Anthony Russo, Joe Russo",
      "year_of_release": 2019,
      "image_link": "https://example.com/avengers_endgame.jpg",
      "duration": "3h 1min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt4154796/"
    },
    {
      "movie_name": "Pulp Fiction",
      "male_lead": "John Travolta",
      "female_lead": "Uma Thurman",
      "director": "Quentin Tarantino",
      "year_of_release": 1994,
      "image_link": "https://example.com/pulp_fiction.jpg",
      "duration": "2h 34min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0110912/"
    },
    {
      "movie_name": "Fight Club",
      "male_lead": "Brad Pitt",
      "female_lead": "Helena Bonham Carter",
      "director": "David Fincher",
      "year_of_release": 1999,
      "image_link": "https://example.com/fight_club.jpg",
      "duration": "2h 19min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0137523/"
    },
    {
      "movie_name": "Forrest Gump",
      "male_lead": "Tom Hanks",
      "female_lead": "Robin Wright",
      "director": "Robert Zemeckis",
      "year_of_release": 1994,
      "image_link": "https://example.com/forrest_gump.jpg",
      "duration": "2h 22min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0109830/"
    },
    {
      "movie_name": "The Lord of the Rings: The Return of the King",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2003,
      "image_link": "https://example.com/lotr_return_of_the_king.jpg",
      "duration": "3h 21min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0167260/"
    },
    {
      "movie_name": "The Matrix",
      "male_lead": "Keanu Reeves",
      "female_lead": "Carrie-Anne Moss",
      "director": "The Wachowskis",
      "year_of_release": 1999,
      "image_link": "https://example.com/the_matrix.jpg",
      "duration": "2h 16min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0133093/"
    },
    {
      "movie_name": "The Lord of the Rings: The Fellowship of the Ring",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2001,
      "image_link": "https://example.com/lotr_fellowship_of_the_ring.jpg",
      "duration": "2h 58min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0120737/"
    },
    {
      "movie_name": "The Lord of the Rings: The Two Towers",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2002,
      "image_link": "https://example.com/lotr_two_towers.jpg",
      "duration": "2h 59min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0167261/"
    },
    {
      "movie_name": "The Godfather: Part II",
      "male_lead": "Al Pacino",
      "female_lead": "Diane Keaton",
      "director": "Francis Ford Coppola",
      "year_of_release": 1974,
      "image_link": "https://example.com/the_godfather_part_ii.jpg",
      "duration": "3h 22min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0071562/"
    },
    {
      "movie_name": "Interstellar",
      "male_lead": "Matthew McConaughey",
      "female_lead": "Anne Hathaway",
      "director": "Christopher Nolan",
      "year_of_release": 2014,
      "image_link": "https://example.com/interstellar.jpg",
      "duration": "2h 49min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0816692/"
    },
    {
      "movie_name": "Schindler's List",
      "male_lead": "Liam Neeson",
      "female_lead": "Embeth Davidtz",
      "director": "Steven Spielberg",
      "year_of_release": 1993,
      "image_link": "https://example.com/schindlers_list.jpg",
      "duration": "3h 15min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0108052/"
    },
    {
      "movie_name": "The Shawshank Redemption",
      "male_lead": "Tim Robbins",
      "female_lead": "",
      "director": "Frank Darabont",
      "year_of_release": 1994,
      "image_link": "https://example.com/shawshank_redemption.jpg",
      "duration": "2h 22min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0111161/"
    },
    {
      "movie_name": "Forrest Gump",
      "male_lead": "Tom Hanks",
      "female_lead": "Robin Wright",
      "director": "Robert Zemeckis",
      "year_of_release": 1994,
      "image_link": "https://example.com/forrest_gump.jpg",
      "duration": "2h 22min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0109830/"
    },
    {
      "movie_name": "The Lord of the Rings: The Fellowship of the Ring",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2001,
      "image_link": "https://example.com/lotr_fellowship_of_the_ring.jpg",
      "duration": "2h 58min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0120737/"
    },
    {
      "movie_name": "The Dark Knight",
      "male_lead": "Christian Bale",
      "female_lead": "Maggie Gyllenhaal",
      "director": "Christopher Nolan",
      "year_of_release": 2008,
      "image_link": "https://example.com/the_dark_knight.jpg",
      "duration": "2h 32min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0468569/"
    },
    {
      "movie_name": "The Godfather",
      "male_lead": "Marlon Brando",
      "female_lead": "Diane Keaton",
      "director": "Francis Ford Coppola",
      "year_of_release": 1972,
      "image_link": "https://example.com/the_godfather.jpg",
      "duration": "2h 55min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0068646/"
    },
    {
      "movie_name": "Avengers: Endgame",
      "male_lead": "Robert Downey Jr.",
      "female_lead": "Scarlett Johansson",
      "director": "Anthony Russo, Joe Russo",
      "year_of_release": 2019,
      "image_link": "https://example.com/avengers_endgame.jpg",
      "duration": "3h 1min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt4154796/"
    },
    {
      "movie_name": "Pulp Fiction",
      "male_lead": "John Travolta",
      "female_lead": "Uma Thurman",
      "director": "Quentin Tarantino",
      "year_of_release": 1994,
      "image_link": "https://example.com/pulp_fiction.jpg",
      "duration": "2h 34min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0110912/"
    },
    {
      "movie_name": "Fight Club",
      "male_lead": "Brad Pitt",
      "female_lead": "Helena Bonham Carter",
      "director": "David Fincher",
      "year_of_release": 1999,
      "image_link": "https://example.com/fight_club.jpg",
      "duration": "2h 19min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0137523/"
    },
    {
      "movie_name": "The Lord of the Rings: The Return of the King",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2003,
      "image_link": "https://example.com/lotr_return_of_the_king.jpg",
      "duration": "3h 21min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0167260/"
    },
    {
      "movie_name": "The Matrix",
      "male_lead": "Keanu Reeves",
      "female_lead": "Carrie-Anne Moss",
      "director": "The Wachowskis",
      "year_of_release": 1999,
      "image_link": "https://example.com/the_matrix.jpg",
      "duration": "2h 16min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0133093/"
    },
    {
      "movie_name": "The Lord of the Rings: The Two Towers",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2002,
      "image_link": "https://example.com/lotr_two_towers.jpg",
      "duration": "2h 59min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0167261/"
    },
    {
      "movie_name": "The Godfather: Part II",
      "male_lead": "Al Pacino",
      "female_lead": "Diane Keaton",
      "director": "Francis Ford Coppola",
      "year_of_release": 1974,
      "image_link": "https://example.com/the_godfather_part_ii.jpg",
      "duration": "3h 22min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0071562/"
    },
    {
      "movie_name": "Interstellar",
      "male_lead": "Matthew McConaughey",
      "female_lead": "Anne Hathaway",
      "director": "Christopher Nolan",
      "year_of_release": 2014,
      "image_link": "https://example.com/interstellar.jpg",
      "duration": "2h 49min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0816692/"
    },
    {
      "movie_name": "Schindler's List",
      "male_lead": "Liam Neeson",
      "female_lead": "Embeth Davidtz",
      "director": "Steven Spielberg",
      "year_of_release": 1993,
      "image_link": "https://example.com/schindlers_list.jpg",
      "duration": "3h 15min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0108052/"
    },
    {
      "movie_name": "Forrest Gump",
      "male_lead": "Tom Hanks",
      "female_lead": "Robin Wright",
      "director": "Robert Zemeckis",
      "year_of_release": 1994,
      "image_link": "https://example.com/forrest_gump.jpg",
      "duration": "2h 22min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0109830/"
    },
    {
      "movie_name": "The Lord of the Rings: The Fellowship of the Ring",
      "male_lead": "Elijah Wood",
      "female_lead": "Liv Tyler",
      "director": "Peter Jackson",
      "year_of_release": 2001,
      "image_link": "https://example.com/lotr_fellowship_of_the_ring.jpg",
      "duration": "2h 58min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0120737/"
    },
    {
      "movie_name": "The Dark Knight",
      "male_lead": "Christian Bale",
      "female_lead": "Maggie Gyllenhaal",
      "director": "Christopher Nolan",
      "year_of_release": 2008,
      "image_link": "https://example.com/the_dark_knight.jpg",
      "duration": "2h 32min",
      "age_rating": "PG-13",
      "imdb_link": "https://www.imdb.com/title/tt0468569/"
    },
    {
      "movie_name": "The Godfather",
      "male_lead": "Marlon Brando",
      "female_lead": "Diane Keaton",
      "director": "Francis Ford Coppola",
      "year_of_release": 1972,
      "image_link": "https://example.com/the_godfather.jpg",
      "duration": "2h 55min",
      "age_rating": "R",
      "imdb_link": "https://www.imdb.com/title/tt0068646/"
    }
  ]
  